apiVersion: v1
kind: ConfigMap
metadata:
  name: ap-coworking-configmap
data:
  DB_NAME: mydatabase
  DB_USERNAME: myuser
  DB_HOST: postgresql-service
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: ap-psql-pass
type: Opaque
data:
  password: bXlwYXNzd29yZA==